# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: blockscore 4.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "blockscore"
  s.version = "4.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = [
    "Alain Meier", "John Backus", "Connor Jacobsen", "Henk Tillman",
    "Ben Schwartz", "Dave Marshall", "Karol Sarnacki", "Hamish Eisler"
  ]
  s.date = "2015-05-16"
  s.description = "A ruby client library for the BlockScore API."
  s.email = "alain@blockscore.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = `git ls-files`.split("\n")
  s.homepage = "http://github.com/blockscore/blockscore-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A ruby client library for the BlockScore API."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.11"])
      s.add_development_dependency(%q<shoulda>, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<minitest>, ["~> 4.0"])
      s.add_development_dependency(%q<shoulda-context>, ["~> 1.2"])
      s.add_development_dependency(%q<test-unit>, ["3.0"])
      s.add_development_dependency(%q<test-unit-activesupport>, ["1.0"])
      s.add_development_dependency(%q<webmock>, ["1.21"])
      s.add_development_dependency(%q<faker>, ["1.4.3"])
      s.add_development_dependency(%q<factory_girl>, ["4.1.0"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.11"])
      s.add_dependency(%q<shoulda>, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<minitest>, ["~> 4.0"])
      s.add_dependency(%q<shoulda-context>, ["~> 1.2"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.11"])
    s.add_dependency(%q<shoulda>, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<minitest>, ["~> 4.0"])
    s.add_dependency(%q<shoulda-context>, ["~> 1.2"])
  end
end

